<?php
  // ROOT  WITHOUT '/' at the end of string
  define("ROOT_PATH","/var/www/regheat"); 
  // GRAPHS, generated by pChart
  define("GRAPHS_PATH",ROOT_PATH."/pic/stats/");
  define("STAT_GRAPHS_PATH",ROOT_PATH."/pic/stats/");
  // SCRIPTS 
  define("SCRIPTS_PATH",ROOT_PATH."/scripts");
  define("SCRIPT_GRAPHS_PATH",ROOT_PATH."/grafy/");
  // LOG file
  define("LOG_PATH",ROOT_PATH."/scripts/log.txt");
  // uSDS, SDS,... 
  //define("SDS_ADDRESS",'http://192.168.111.183/');
  define("SDS_ADDRESS",'http://192.168.1.2/');
  define("ZONE_ADC_LEVEL_TO_ON",'70');
?>
